import functools
import json
import os
import re

from .common import InfoExtractor
from ..utils import ass_subtitles_timecode, float_or_none, parse_iso8601, str_or_none, traverse_obj, url_or_none


class LividIE(InfoExtractor):
    _VALID_URL = r'https?://(?:www\.)?livid\.com/(?:watch|embed)/(?P<id>[0-9A-Za-z]+)'
    _TESTS = [{
        'url': 'https://livid.com/watch/J09eQruc7E6u',
        'info_dict': {
            'id': 'J09eQruc7E6u',
            'ext': 'mp4',
            'title': 'Livid Analytics',
            'description': 'md5:2610fc3ff2deeb427051efcd86411614',
            'thumbnail': r're:https?://api\.livid\.com/v1/thumbnails/.*\.jpg$',
            'uploader_id': 'f0d8c8430a7340b09355e9c9ca629afd',
            'duration': 19,
            'timestamp': 1774525149,
            'upload_date': '20260326',
        },
        'params': {
            'skip_download': True,
        },
    }, {
        'note': 'Embed link some metadata is missing',
        'url': 'https://livid.com/embed/lDlnp0fM1omO',
        'md5': 'e6736151653f657b4d7069a77f7cd716',
        'info_dict': {
            'id': 'lDlnp0fM1omO',
            'ext': 'mp4',
            'title': 'youtube-dl test video ＂\'⧸⧹ä↭𝕐 [BaW_jenozKc]',
            'description': 'md5:ebb3481475b337bdffae01644f2f9280',
            'thumbnail': r're:https?://api\.livid\.com/v1/thumbnails/.*\.jpg$',
            'uploader_id': '9eebf39a8c1d43819626b266e718a445',
            'timestamp': 1788791315,
            'upload_date': '20260907',
        },
        'params': {
            'skip_download': True,
        },
    }, {
        'url': 'https://livid.com/watch/T3PPnfE7UKk8',
        'info_dict': {
            'id': 'T3PPnfE7UKk8',
            'ext': 'mp4',
        },
        'skip': 'Private video',
    }]

    def _fetch_subtitles(self, uuid: str, transcripts: dict, video_id: str, is_auto_subs: bool = False) -> dict[str, list[dict]]:
        subtitles = {}
        for transcript in transcripts.get('transcripts', []):
            if ((is_auto_subs is False and transcript.get('source') == 'auto')
                    or (is_auto_subs and transcript.get('source') != 'auto')):
                continue
            language = traverse_obj(transcript, ('language', {str_or_none}))
            segments = traverse_obj(
                self._download_json(f'https://api.livid.com/v1/videos/id/{uuid}/transcript-segments?language={language}', video_id),
                ('segments', {list}))
            if segments is None:
                continue
            if language == 'unknown':
                language = 'und'
            subtitles[language] = [
                {'ext': 'json', 'data': json.dumps(segments)},
                {'ext': 'ass', 'data': self._generate_ass_subtitles(segments)},
            ]
        return subtitles

    _get_subtitles = functools.partialmethod(_fetch_subtitles, is_auto_subs=False)
    _get_automatic_captions = functools.partialmethod(_fetch_subtitles, is_auto_subs=True)

    def _generate_ass_subtitles(self, segments: list[dict[str, float | str]]):
        ass = f'''[Script Info]
; Script generated by `{self.__class__.__module__}.{self.__class__.__qualname__}`
ScriptType: v4.00+
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'''
        for segment in segments:
            start, end, text = (
                float_or_none(segment.get('start')),
                float_or_none(segment.get('end')),
                str_or_none(segment.get('text')))
            if start is None or end is None or text is None:
                continue
            ass += os.linesep + f'Dialogue: Marked=0,{ass_subtitles_timecode(start)},{ass_subtitles_timecode(end)},Default,,0,0,0,,{text}'
        return ass

    def _real_extract(self, url):
        video_id = self._match_id(url)
        webpage = self._download_webpage(url, video_id)

        if 'Sorry, we couldn’t find that video' in webpage:
            self.raise_login_required('This video is private')

        json_ld = self._search_json_ld(webpage, video_id, fatal=False, default={})
        title = json_ld.get('title') or self._generic_title(url, webpage)
        description = (json_ld.get('description')
                       or self._search_regex(r'descriptionText\s*:\s*(["\'])(?P<description>[^"\']*)\1',
                                             webpage, 'description', fatal=False, default=None)
                       or self._html_search_meta(['description', 'og:description', 'twitter:description'], webpage))
        uploader_id = self._search_regex(r'organizationId\s*:\s*(["\'])(?P<uploader_id>[^"\']*)\1',
                                         webpage, 'uploader id', default=None, group='uploader_id')
        timestamp = (json_ld.get('timestamp')
                     or parse_iso8601(self._search_regex(r'createdAt\s*:\s*(["\'])(?P<upload_date>[^"\']*)\1',
                                                         webpage, 'upload date', default=None, group='upload_date')))
        small_thumbnail = self._search_regex(r'srcSmall\s*:\s*(["\'])(?P<url>[^"\']*)\1', webpage, 'thumbnail url', group='url')

        m3u8_url = self._search_regex(r'src\s*:\s*(["\'])(?P<url>[^"\']*m3u8)\1', webpage, 'm3u8 url', group='url')
        formats, subtitles = self._extract_m3u8_formats_and_subtitles(m3u8_url, video_id)
        for liste in subtitles.values():
            for sub_dict in liste:
                sub_dict.setdefault('id', video_id)
        uuid = traverse_obj(re.findall(r'id\s*:\s*(["\'])(?P<id>[^"\']*)\1', webpage), (2, 1))
        transcripts = self._download_json(f'https://api.livid.com/v1/videos/id/{uuid}/transcripts', video_id) or {}

        subs2 = self.extract_subtitles(uuid, transcripts, video_id)
        for lang, value in subs2.items():
            subtitles.setdefault(lang, []).extend(value)

        thumbnails = json_ld.get('thumbnails', [])
        thumbnails.extend([
            {'url': url_or_none(self._og_search_thumbnail(webpage))},
            {'url': small_thumbnail, 'preference': -2},
        ])

        return {
            'id': video_id,
            'title': title,
            'description': description,
            'thumbnails': thumbnails,
            'timestamp': timestamp,
            'duration': json_ld.get('duration'),
            'width': json_ld.get('width'),
            'height': json_ld.get('height'),
            'formats': formats,
            'subtitles': subtitles,
            'automatic_captions': self.extract_automatic_captions(uuid, transcripts, video_id),
            'uploader_id': uploader_id,
        }
