from yt_dlp.dependencies import protobug


class SeekSource(protobug.Enum, strict=False):
    UNKNOWN = 0
    SABR_PARTIAL_CHUNK = 9
    SABR_SEEK_TO_HEAD = 10
    SABR_LIVE_DVR_USER_SEEK = 11
    SABR_SEEK_TO_DVR_LOWER_BOUND = 12
    SABR_SEEK_TO_DVR_UPPER_BOUND = 13
    SABR_ACCURATE_SEEK = 17
    SABR_INGESTION_WALL_TIME_SEEK = 29
    SABR_SEEK_TO_CLOSEST_KEYFRAME = 59
    SABR_RELOAD_PLAYER_RESPONSE_TOKEN_SEEK = 106
