from yt_dlp.dependencies import protobug


class SeekSource(protobug.Enum, strict=False):
    SEEK_SOURCE_UNKNOWN = 0
    SEEK_SOURCE_SABR_PARTIAL_CHUNK = 9
    SEEK_SOURCE_SABR_SEEK_TO_HEAD = 10
    SEEK_SOURCE_SABR_LIVE_DVR_USER_SEEK = 11
    SEEK_SOURCE_SABR_SEEK_TO_DVR_LOWER_BOUND = 12
    SEEK_SOURCE_SABR_SEEK_TO_DVR_UPPER_BOUND = 13
    SEEK_SOURCE_SABR_ACCURATE_SEEK = 17
    SEEK_SOURCE_SABR_INGESTION_WALL_TIME_SEEK = 29
    SEEK_SOURCE_SABR_SEEK_TO_CLOSEST_KEYFRAME = 59
    SEEK_SOURCE_SABR_RELOAD_PLAYER_RESPONSE_TOKEN_SEEK = 106
