# Autogenerated by devscripts/update-version.py

__version__ = '2026.01.31'

RELEASE_GIT_HEAD = '9a9a6b6fe44a30458c1754ef064f354f04a84004'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'yt-dlp/yt-dlp'

_pkg_version = '2026.01.31'
