# Autogenerated by devscripts/update-version.py

__version__ = '2024.10.07'

RELEASE_GIT_HEAD = '1a176d874e6772cd898ce507379ea388e96ee3f7'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'yt-dlp/yt-dlp'

_pkg_version = '2024.10.07'
