# Autogenerated by devscripts/update-version.py

__version__ = '2025.11.12'

RELEASE_GIT_HEAD = '335653be82d5ef999cfc2879d005397402eebec1'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'yt-dlp/yt-dlp'

_pkg_version = '2025.11.12'
