#!/usr/bin/env python3

# Allow direct execution
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


import argparse
import contextlib
import subprocess
import sys
from datetime import datetime

from devscripts.utils import read_version, write_file


def get_new_version(version, revision):
    if not version:
        version = datetime.utcnow().strftime('%Y.%m.%d')

    if revision:
        assert revision.isdigit(), 'Revision must be a number'
    else:
        old_version = read_version().split('.')
        if version.split('.') == old_version[:3]:
            revision = str(int((old_version + [0])[3]) + 1)

    return f'{version}.{revision}' if revision else version


def get_git_head():
    with contextlib.suppress(Exception):
        return subprocess.check_output(['git', 'rev-parse', 'HEAD'], text=True).strip() or None


VERSION_TEMPLATE = '''\
# Autogenerated by devscripts/update-version.py

__version__ = {version!r}

RELEASE_GIT_HEAD = {git_head!r}

VARIANT = None

UPDATE_HINT = None

CHANNEL = {channel!r}
'''

if __name__=='__main__':
    parser = argparse.ArgumentParser(description='Update the version.py file')
    parser.add_argument(
        '-c', '--channel', choices=['stable', 'nightly'], default='stable',
        help='Select update channel (default: stable)')
    parser.add_argument(
        '-o', '--output', default='yt_dlp/version.py',
        help='The output file to write to (default: yt_dlp/version.py)')
    parser.add_argument(
        'version', nargs='?', default=None,
        help='A full version, version or revision to override generated ones')
    args = parser.parse_args()

    git_head = get_git_head()
    version = (
        get_new_version(None, None) if not args.version
        else args.version if args.version.count('.') == 3  # Full version
        else get_new_version(args.version, None) if args.version.count('.') == 2
        else get_new_version(None, args.version))  # Revision only
    write_file(str(args.output), VERSION_TEMPLATE.format(
        version=version, git_head=git_head, channel=args.channel))

    print(f'Version = {version} ({args.channel}), Git HEAD = {git_head}')
