/**
 * SPDX-License-Identifier: Unlicense
 * This file was automatically generated by https://github.com/yt-dlp/ejs on 2025-09-26T10:10:18.866Z
 */
const lib = {
  meriyah: await import('npm:meriyah@6.1.4'),
  astring: await import('npm:astring@1.9.0'),
};
export { lib };
