name: Issue Lockdown
on:
  issues:
    types: [opened]

permissions: {}

env:
  GH_TELEMETRY: "false"

jobs:
  lockdown:
    name: Issue lockdown
    if: vars.ISSUE_LOCKDOWN
    permissions:
      issues: write  # Needed to lock issues
    runs-on: ubuntu-latest
    steps:
      - name: "Lock new issue"
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY: ${{ github.repository }}
        run: |
          gh issue lock -R "${REPOSITORY}" "${ISSUE_NUMBER}"
