name: Update wiki
on:
  schedule:
    - cron: '22 22 * * *'
  workflow_dispatch:

permissions: {}

concurrency:
  group: wiki
  cancel-in-progress: true

jobs:
  update_wiki:
    name: Update wiki
    if: github.ref == 'refs/heads/master' && github.repository == 'yt-dlp/yt-dlp'
    permissions:
      contents: write  # Needed to git-push to the wiki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: yt-dlp/yt-dlp-wiki
          ref: master
          fetch-depth: 0
          persist-credentials: true  # Needed to git-push to the wiki

      - name: Push to wiki
        run: |
          git remote add upstream https://github.com/yt-dlp/yt-dlp.wiki.git
          git fetch upstream
          git push --force upstream master
